name: dart_builder
author: Matan Lurey <matanl@google.com>
description: A fluent API for creating Dart code.
version: 0.0.1-alpha.1
homepage: https://github.com/matanlurey/dart_builder
dependencies:
  dart_style: ">=0.1.8 <0.2.0"
  mustache: ">=0.2.3 <0.3.0"
dev_dependencies:
  test: any
